### ISSUE TITLE
The theme doesn't change when i change the song

### ISSUE THREAD

**Issue by zengof** [JulienMaille/spicetify-dynamic-theme#25]
When a new song plays the colors of the theme don't change.

They do change when i go to a song after it and go to the previously mentioned song.

there's the video of encountering the issue
https://gyazo.com/08de45e24fb06b43d373ad86a1a60557

win 10
spicetify 2.9.2
dynamic theme 3.5

**Comment by lhvy** [comment]
I'm getting this behaviour too.

**Comment by lhvy** [comment]
After reading a bit more, my guess is the problem is here: https://github.com/JulienMaille/spicetify-dynamic-theme/blob/f843ec3b99f44d71021855e334be846297c3dff2/default-dynamic.js#L13

See here how spicetify-cli made a "temporary" update to their built-in extensions to avoid using the Hermes protocol: https://github.com/spicetify/spicetify-cli/pull/1543

Unfortunately I don't have the knowledge or time currently to read into this and work out a solution to make in a PR. I might check back later but if not, good luck to anyone working on this!
